#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

#export IMPORTANT_ENVIRONMENT_VARIABLE=value

# Finally run the next part of the command chain
if test $# -ne 0; then
    "${@}" || true
else
    :
fi

(
    # Redirect to standard error device to avoid corrupting regular output
    printf -- \
        '\n# %s #\n%s\n\n%s\n\n    %s\n\n' \
        "Snap Obsoletion Notice" \
        \
        "Hello, the \`libxml2-utils\` snap is now obsoleted and will no longer recieve any updates, please remove this snap and install the \`libxml2\` snap instead." \
        \
        "If you have any questions regarding the obsoletion, please refer to the issue tracker:" \
        \
        "https://github.com/Lin-Buo-Ren/libxml2-snap/issues"
) 1>&2
