%YAML 1.1
---
# Snapcraft Recipe for XML Toolkit from the GNOME Project
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: libxml2-utils
title: XML Toolkit from the GNOME Project
summary: XML C parser and toolkit developed for the Gnome project
description: |
  Libxml2 is the XML C parser and toolkit developed for the Gnome project (but usable outside of the Gnome platform), it is free software available under the MIT License.

  This snap ships the latest released and development snapshot of libxml2 itself and expose its command-line utilites to the system.

  This snap is NOT OFFICIAL, for any issue regarding using the snap please refer to the issue tracker:

  https://github.com/Lin-Buo-Ren/libxml2-snap/issues

icon: snap/gui/icon.png
license: MIT

adopt-info: libxml2
base: core
confinement: strict
grade: stable

parts:
  libxml2:
    after:
    - selective-checkout

    source: https://gitlab.gnome.org/GNOME/libxml2.git
    source-depth: 50

    plugin: autotools
    configflags:
    - --disable-dependency-tracking
    build-packages:
    # Required by Python bindings
    - libpython-all-dev
    - python-all-dev

    # DISABLED: Automatically installed by `autotools` plugin
    #- autoconf
    #- automake
    #- libtool-bin
    #- make

    - libicu-dev
    - liblzma-dev
    - pkg-config
    - zlib1g-dev
    stage-packages:
    - libicu55

    # Required by Python bindings
    - libpython2.7

    - liblzma5
    - zlib1g

    override-pull: |
      snapcraftctl pull

      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout \
        --append-packaging-revision

    filesets:
      cmake:
      - lib/cmake/*
      docs-copyright:
      - share/doc/libxml2-*/Copyright
      docs-excluded:
      - -share/doc/*
      - -share/gtk-doc/*
      - -share/man/man3/*
      executables:
      - bin/*
      - etc/*
      files-in-stage-packages:
      - usr/*
      library-headers:
      - include/*
      library-libtool:
      - lib/*.la
      library-pkgconfig:
      - lib/pkgconfig/*
      library-shared:
      - lib/*.so*
      library-static:
      - lib/*.a
      m4:
      - share/aclocal/*.m4

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout
    prime:
    - -*

apps:
  xmllint:
    command: xmllint

  xmlcatalog:
    command: xmlcatalog

plugs:
  # Storage access
  home:
  removable-media:

  # Network access for fetching DTDs or entities over network
  network:
